/*
 * ONE Record API Documentation
 *
 * This OpenAPI specification describes the API endpoint structure of an ONE Record API implementation.<br/><br/><b>Note:</b><br/>The included schemas can only be used to generate JSON-LD in the extended document form.<br/>However, to be fully ONE Record compliant, any ONE Record API (and any compliant ONE Record client)<br/><b>MUST</b> support at least the expanded, compacted, and flattened document forms.<br/><br/>More information about the ONE Record specification are available on [IATA Github repository](https://github.com/IATA-Cargo/ONE-Record) and on the [ONE Record Developer Portal](https://onerecord.iata.org).
 *
 * The version of the OpenAPI document: 2.0.0-dev
 * Contact: onerecord@iata.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace OneRecord.Api.SDK.Model
{
    /// <summary>
    /// Adjustments
    /// </summary>
    [DataContract(Name = "Adjustments")]
    public partial class Adjustments : IEquatable<Adjustments>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Adjustments" /> class.
        /// </summary>
        /// <param name="httpsId">id.</param>
        /// <param name="httpsType">type.</param>
        /// <param name="httpsCargocorrectionNumber">CargocorrectionNumber.</param>
        /// <param name="httpsCargocorrectionSerialNumber">CargocorrectionSerialNumber.</param>
        /// <param name="httpsCargoreasonsForAdjustments">CargoreasonsForAdjustments.</param>
        public Adjustments(string httpsId = default(string), List<string> httpsType = default(List<string>), int httpsCargocorrectionNumber = default(int), string httpsCargocorrectionSerialNumber = default(string), string httpsCargoreasonsForAdjustments = default(string))
        {
            this.HttpsId = httpsId;
            this.HttpsType = httpsType;
            this.HttpsCargocorrectionNumber = httpsCargocorrectionNumber;
            this.HttpsCargocorrectionSerialNumber = httpsCargocorrectionSerialNumber;
            this.HttpsCargoreasonsForAdjustments = httpsCargoreasonsForAdjustments;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "@id", EmitDefaultValue = false)]
        public string HttpsId { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "@type", EmitDefaultValue = false)]
        public List<string> HttpsType { get; set; }

        /// <summary>
        /// Gets or Sets CargocorrectionNumber
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#correctionNumber", EmitDefaultValue = false)]
        public int HttpsCargocorrectionNumber { get; set; }

        /// <summary>
        /// Gets or Sets CargocorrectionSerialNumber
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#correctionSerialNumber", EmitDefaultValue = false)]
        public string HttpsCargocorrectionSerialNumber { get; set; }

        /// <summary>
        /// Gets or Sets CargoreasonsForAdjustments
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#reasonsForAdjustments", EmitDefaultValue = false)]
        public string HttpsCargoreasonsForAdjustments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Adjustments {\n");
            sb.Append("  Id: ").Append(HttpsId).Append("\n");
            sb.Append("  Type: ").Append(HttpsType).Append("\n");
            sb.Append("  CargocorrectionNumber: ").Append(HttpsCargocorrectionNumber).Append("\n");
            sb.Append("  CargocorrectionSerialNumber: ").Append(HttpsCargocorrectionSerialNumber).Append("\n");
            sb.Append("  CargoreasonsForAdjustments: ").Append(HttpsCargoreasonsForAdjustments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="httpsInput">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object httpsInput)
        {
            return this.Equals(httpsInput as Adjustments);
        }

        /// <summary>
        /// Returns true if Adjustments instances are equal
        /// </summary>
        /// <param name="httpsInput">Instance of Adjustments to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Adjustments httpsInput)
        {
            if (httpsInput == null)
            {
                return false;
            }
            return 
                (
                    this.HttpsId == httpsInput.HttpsId ||
                    (this.HttpsId != null &&
                    this.HttpsId.Equals(httpsInput.HttpsId))
                ) && 
                (
                    this.HttpsType == httpsInput.HttpsType ||
                    this.HttpsType != null &&
                    httpsInput.HttpsType != null &&
                    this.HttpsType.SequenceEqual(httpsInput.HttpsType)
                ) && 
                (
                    this.HttpsCargocorrectionNumber == httpsInput.HttpsCargocorrectionNumber ||
                    this.HttpsCargocorrectionNumber.Equals(httpsInput.HttpsCargocorrectionNumber)
                ) && 
                (
                    this.HttpsCargocorrectionSerialNumber == httpsInput.HttpsCargocorrectionSerialNumber ||
                    (this.HttpsCargocorrectionSerialNumber != null &&
                    this.HttpsCargocorrectionSerialNumber.Equals(httpsInput.HttpsCargocorrectionSerialNumber))
                ) && 
                (
                    this.HttpsCargoreasonsForAdjustments == httpsInput.HttpsCargoreasonsForAdjustments ||
                    (this.HttpsCargoreasonsForAdjustments != null &&
                    this.HttpsCargoreasonsForAdjustments.Equals(httpsInput.HttpsCargoreasonsForAdjustments))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HttpsId != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsId.GetHashCode();
                }
                if (this.HttpsType != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsType.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.HttpsCargocorrectionNumber.GetHashCode();
                if (this.HttpsCargocorrectionSerialNumber != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargocorrectionSerialNumber.GetHashCode();
                }
                if (this.HttpsCargoreasonsForAdjustments != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargoreasonsForAdjustments.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="httpsValidationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext httpsValidationContext)
        {
            yield break;
        }
    }

}
