/*
 * ONE Record API Documentation
 *
 * This OpenAPI specification describes the API endpoint structure of an ONE Record API implementation.<br/><br/><b>Note:</b><br/>The included schemas can only be used to generate JSON-LD in the extended document form.<br/>However, to be fully ONE Record compliant, any ONE Record API (and any compliant ONE Record client)<br/><b>MUST</b> support at least the expanded, compacted, and flattened document forms.<br/><br/>More information about the ONE Record specification are available on [IATA Github repository](https://github.com/IATA-Cargo/ONE-Record) and on the [ONE Record Developer Portal](https://onerecord.iata.org).
 *
 * The version of the OpenAPI document: 2.0.0-dev
 * Contact: onerecord@iata.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace OneRecord.Api.SDK.Model
{
    /// <summary>
    /// Answer
    /// </summary>
    [DataContract(Name = "Answer")]
    public partial class Answer : IEquatable<Answer>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Answer" /> class.
        /// </summary>
        /// <param name="httpsId">id.</param>
        /// <param name="httpsType">type.</param>
        /// <param name="httpsCargochecks">Cargochecks.</param>
        /// <param name="httpsCargoevents">Cargoevents.</param>
        /// <param name="httpsCargoexternalReferences">CargoexternalReferences.</param>
        /// <param name="httpsCargocompanyIdentifier">CargocompanyIdentifier.</param>
        /// <param name="httpsCargoskeletonIndicator">CargoskeletonIndicator.</param>
        /// <param name="httpsCargoanswerActor">CargoanswerActor.</param>
        /// <param name="httpsCargoanswerValue">CargoanswerValue.</param>
        /// <param name="httpsCargogivenAtLocation">CargogivenAtLocation.</param>
        /// <param name="httpsCargoinvolvedParties">CargoinvolvedParties.</param>
        /// <param name="httpsCargoquestion">Cargoquestion.</param>
        /// <param name="httpsCargotext">Cargotext.</param>
        public Answer(string httpsId = default(string), List<string> httpsType = default(List<string>), List<Check> httpsCargochecks = default(List<Check>), List<LogisticsEvent> httpsCargoevents = default(List<LogisticsEvent>), List<ExternalReference> httpsCargoexternalReferences = default(List<ExternalReference>), string httpsCargocompanyIdentifier = default(string), bool httpsCargoskeletonIndicator = default(bool), Actor httpsCargoanswerActor = default(Actor), Value httpsCargoanswerValue = default(Value), Location httpsCargogivenAtLocation = default(Location), List<Party> httpsCargoinvolvedParties = default(List<Party>), Question httpsCargoquestion = default(Question), string httpsCargotext = default(string))
        {
            this.HttpsId = httpsId;
            this.HttpsType = httpsType;
            this.HttpsCargochecks = httpsCargochecks;
            this.HttpsCargoevents = httpsCargoevents;
            this.HttpsCargoexternalReferences = httpsCargoexternalReferences;
            this.HttpsCargocompanyIdentifier = httpsCargocompanyIdentifier;
            this.HttpsCargoskeletonIndicator = httpsCargoskeletonIndicator;
            this.HttpsCargoanswerActor = httpsCargoanswerActor;
            this.HttpsCargoanswerValue = httpsCargoanswerValue;
            this.HttpsCargogivenAtLocation = httpsCargogivenAtLocation;
            this.HttpsCargoinvolvedParties = httpsCargoinvolvedParties;
            this.HttpsCargoquestion = httpsCargoquestion;
            this.HttpsCargotext = httpsCargotext;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "@id", EmitDefaultValue = false)]
        public string HttpsId { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "@type", EmitDefaultValue = false)]
        public List<string> HttpsType { get; set; }

        /// <summary>
        /// Gets or Sets Cargochecks
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#checks", EmitDefaultValue = false)]
        public List<Check> HttpsCargochecks { get; set; }

        /// <summary>
        /// Gets or Sets Cargoevents
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#events", EmitDefaultValue = false)]
        public List<LogisticsEvent> HttpsCargoevents { get; set; }

        /// <summary>
        /// Gets or Sets CargoexternalReferences
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#externalReferences", EmitDefaultValue = false)]
        public List<ExternalReference> HttpsCargoexternalReferences { get; set; }

        /// <summary>
        /// Gets or Sets CargocompanyIdentifier
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#companyIdentifier", EmitDefaultValue = false)]
        public string HttpsCargocompanyIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets CargoskeletonIndicator
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#skeletonIndicator", EmitDefaultValue = true)]
        public bool HttpsCargoskeletonIndicator { get; set; }

        /// <summary>
        /// Gets or Sets CargoanswerActor
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#answerActor", EmitDefaultValue = false)]
        public Actor HttpsCargoanswerActor { get; set; }

        /// <summary>
        /// Gets or Sets CargoanswerValue
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#answerValue", EmitDefaultValue = false)]
        public Value HttpsCargoanswerValue { get; set; }

        /// <summary>
        /// Gets or Sets CargogivenAtLocation
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#givenAtLocation", EmitDefaultValue = false)]
        public Location HttpsCargogivenAtLocation { get; set; }

        /// <summary>
        /// Gets or Sets CargoinvolvedParties
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#involvedParties", EmitDefaultValue = false)]
        public List<Party> HttpsCargoinvolvedParties { get; set; }

        /// <summary>
        /// Gets or Sets Cargoquestion
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#question", EmitDefaultValue = false)]
        public Question HttpsCargoquestion { get; set; }

        /// <summary>
        /// Gets or Sets Cargotext
        /// </summary>
        [DataMember(Name = "https://onerecord.iata.org/ns/cargo#text", EmitDefaultValue = false)]
        public string HttpsCargotext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Answer {\n");
            sb.Append("  Id: ").Append(HttpsId).Append("\n");
            sb.Append("  Type: ").Append(HttpsType).Append("\n");
            sb.Append("  Cargochecks: ").Append(HttpsCargochecks).Append("\n");
            sb.Append("  Cargoevents: ").Append(HttpsCargoevents).Append("\n");
            sb.Append("  CargoexternalReferences: ").Append(HttpsCargoexternalReferences).Append("\n");
            sb.Append("  CargocompanyIdentifier: ").Append(HttpsCargocompanyIdentifier).Append("\n");
            sb.Append("  CargoskeletonIndicator: ").Append(HttpsCargoskeletonIndicator).Append("\n");
            sb.Append("  CargoanswerActor: ").Append(HttpsCargoanswerActor).Append("\n");
            sb.Append("  CargoanswerValue: ").Append(HttpsCargoanswerValue).Append("\n");
            sb.Append("  CargogivenAtLocation: ").Append(HttpsCargogivenAtLocation).Append("\n");
            sb.Append("  CargoinvolvedParties: ").Append(HttpsCargoinvolvedParties).Append("\n");
            sb.Append("  Cargoquestion: ").Append(HttpsCargoquestion).Append("\n");
            sb.Append("  Cargotext: ").Append(HttpsCargotext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="httpsInput">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object httpsInput)
        {
            return this.Equals(httpsInput as Answer);
        }

        /// <summary>
        /// Returns true if Answer instances are equal
        /// </summary>
        /// <param name="httpsInput">Instance of Answer to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Answer httpsInput)
        {
            if (httpsInput == null)
            {
                return false;
            }
            return 
                (
                    this.HttpsId == httpsInput.HttpsId ||
                    (this.HttpsId != null &&
                    this.HttpsId.Equals(httpsInput.HttpsId))
                ) && 
                (
                    this.HttpsType == httpsInput.HttpsType ||
                    this.HttpsType != null &&
                    httpsInput.HttpsType != null &&
                    this.HttpsType.SequenceEqual(httpsInput.HttpsType)
                ) && 
                (
                    this.HttpsCargochecks == httpsInput.HttpsCargochecks ||
                    this.HttpsCargochecks != null &&
                    httpsInput.HttpsCargochecks != null &&
                    this.HttpsCargochecks.SequenceEqual(httpsInput.HttpsCargochecks)
                ) && 
                (
                    this.HttpsCargoevents == httpsInput.HttpsCargoevents ||
                    this.HttpsCargoevents != null &&
                    httpsInput.HttpsCargoevents != null &&
                    this.HttpsCargoevents.SequenceEqual(httpsInput.HttpsCargoevents)
                ) && 
                (
                    this.HttpsCargoexternalReferences == httpsInput.HttpsCargoexternalReferences ||
                    this.HttpsCargoexternalReferences != null &&
                    httpsInput.HttpsCargoexternalReferences != null &&
                    this.HttpsCargoexternalReferences.SequenceEqual(httpsInput.HttpsCargoexternalReferences)
                ) && 
                (
                    this.HttpsCargocompanyIdentifier == httpsInput.HttpsCargocompanyIdentifier ||
                    (this.HttpsCargocompanyIdentifier != null &&
                    this.HttpsCargocompanyIdentifier.Equals(httpsInput.HttpsCargocompanyIdentifier))
                ) && 
                (
                    this.HttpsCargoskeletonIndicator == httpsInput.HttpsCargoskeletonIndicator ||
                    this.HttpsCargoskeletonIndicator.Equals(httpsInput.HttpsCargoskeletonIndicator)
                ) && 
                (
                    this.HttpsCargoanswerActor == httpsInput.HttpsCargoanswerActor ||
                    (this.HttpsCargoanswerActor != null &&
                    this.HttpsCargoanswerActor.Equals(httpsInput.HttpsCargoanswerActor))
                ) && 
                (
                    this.HttpsCargoanswerValue == httpsInput.HttpsCargoanswerValue ||
                    (this.HttpsCargoanswerValue != null &&
                    this.HttpsCargoanswerValue.Equals(httpsInput.HttpsCargoanswerValue))
                ) && 
                (
                    this.HttpsCargogivenAtLocation == httpsInput.HttpsCargogivenAtLocation ||
                    (this.HttpsCargogivenAtLocation != null &&
                    this.HttpsCargogivenAtLocation.Equals(httpsInput.HttpsCargogivenAtLocation))
                ) && 
                (
                    this.HttpsCargoinvolvedParties == httpsInput.HttpsCargoinvolvedParties ||
                    this.HttpsCargoinvolvedParties != null &&
                    httpsInput.HttpsCargoinvolvedParties != null &&
                    this.HttpsCargoinvolvedParties.SequenceEqual(httpsInput.HttpsCargoinvolvedParties)
                ) && 
                (
                    this.HttpsCargoquestion == httpsInput.HttpsCargoquestion ||
                    (this.HttpsCargoquestion != null &&
                    this.HttpsCargoquestion.Equals(httpsInput.HttpsCargoquestion))
                ) && 
                (
                    this.HttpsCargotext == httpsInput.HttpsCargotext ||
                    (this.HttpsCargotext != null &&
                    this.HttpsCargotext.Equals(httpsInput.HttpsCargotext))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HttpsId != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsId.GetHashCode();
                }
                if (this.HttpsType != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsType.GetHashCode();
                }
                if (this.HttpsCargochecks != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargochecks.GetHashCode();
                }
                if (this.HttpsCargoevents != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargoevents.GetHashCode();
                }
                if (this.HttpsCargoexternalReferences != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargoexternalReferences.GetHashCode();
                }
                if (this.HttpsCargocompanyIdentifier != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargocompanyIdentifier.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.HttpsCargoskeletonIndicator.GetHashCode();
                if (this.HttpsCargoanswerActor != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargoanswerActor.GetHashCode();
                }
                if (this.HttpsCargoanswerValue != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargoanswerValue.GetHashCode();
                }
                if (this.HttpsCargogivenAtLocation != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargogivenAtLocation.GetHashCode();
                }
                if (this.HttpsCargoinvolvedParties != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargoinvolvedParties.GetHashCode();
                }
                if (this.HttpsCargoquestion != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargoquestion.GetHashCode();
                }
                if (this.HttpsCargotext != null)
                {
                    hashCode = (hashCode * 59) + this.HttpsCargotext.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="httpsValidationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext httpsValidationContext)
        {
            yield break;
        }
    }

}
