/**
 * OneCheck.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OriginPreparationSheetDto } from './originPreparationSheetDto';
import { DestinationHandlingAgentSheetDto } from './destinationHandlingAgentSheetDto';
import { TransitCheckSheetDto } from './transitCheckSheetDto';
import { OriginHandlingAgentSheetDto } from './originHandlingAgentSheetDto';
import { DestinationConsigneeSheetDto } from './destinationConsigneeSheetDto';


export interface SheetDto { 
    checkSheetId?: string;
    preparationSheet?: OriginPreparationSheetDto;
    originHandlingAgentSheet?: OriginHandlingAgentSheetDto;
    inboundTransitSheets?: Array<TransitCheckSheetDto> | null;
    destinationHandlingAgentSheet?: DestinationHandlingAgentSheetDto;
    destinationConsigneeSheet?: DestinationConsigneeSheetDto;
}

