import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Checksheet } from '../../checksheet/models/mockChecksheetModel';
import { ShipmentDto } from 'src/model/shipmentDto';
import { SheetDto } from 'src/model/sheetDto';

@Injectable({
  providedIn: 'root',
})
export class ScanService {
  public constructor(private http: HttpClient) {}

  public getULDs(shipmentCode: string) {
    //return this.http.get(`https://cat-fact.herokuapp.com/facts/`);
    return of({
      checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
      preparationSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'string',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        uldNumber: 'ULD1',
        awbNumber: 0,
        isBatteryCharged: true,
        isContainerDamaged: true,
        routing: ['string'],
        goodsPrecooledAtTemps: 0,
        uldPrecooledTemp: 0,
        tempSetting: 0,
        acceptedTempRange: 0,
        emergencyPhone: 'string',
      },
      originHandlingAgentSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'string',
        signature: 'string',
        name: 'Hansi',
        batteryStatusInPercent: 0,
        isContainerDamaged: true,
        isContainerOperating: true,
        displayTemp: 0,
        isAlert: true,
        isBlueLightOn: 0,
        alertDisplayed: 'string',
        setTempOnDisplay: 0,
        is5AdaptersPresents: true,
      },
      inboundTransitSheets: [
        {
          checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
          date: {
            year: 0,
            month: 0,
            day: 0,
            dayOfWeek: 0,
            dayOfYear: 0,
            dayNumber: 0,
          },
          time: {
            hour: 0,
            minute: 0,
            second: 0,
            millisecond: 0,
            microsecond: 0,
            nanosecond: 0,
            ticks: 0,
          },
          sealNumber: 'string',
          signature: 'string',
          name: 'hansi',
          batteryStatusInPercent: 0,
          inboundCheckAirport: 'string',
          isContainerOperating: true,
          isContainerDamaged: true,
          displayedTemp: 0,
          blueLight: 0,
          isAlarmDisplayed: true,
        },
      ],
      destinationHandlingAgentSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'string',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        inboundCheckAirport: 'string',
        isContainerOperating: true,
        isContainerDamaged: true,
        displayedTemp: 0,
        inboundCheckAirportCode: 'string',
        blueLight: 0,
        isAlarmDisplayed: true,
        setTempOnDisplay: 0,
      },
      destinationConsigneeSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'string',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        isContainerDamaged: true,
        isContainerOperating: true,
        displayTemp: 0,
        is5AdaptersPresents: true,
        recipientname: 'hansi',
        recipientSignature: 'string',
      },
    });
  }

  public mockgetChecksheet(uldId: string): Observable<SheetDto> {
    return of({
      checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
      preparationSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'string',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        uldNumber: 'ULD1',
        awbNumber: 0,
        isBatteryCharged: true,
        isContainerDamaged: true,
        routing: ['string'],
        goodsPrecooledAtTemps: 0,
        uldPrecooledTemp: 0,
        tempSetting: 0,
        acceptedTempRange: 0,
        emergencyPhone: 'string',
      },
      originHandlingAgentSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'string',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        isContainerDamaged: true,
        isContainerOperating: true,
        displayTemp: 0,
        isAlert: true,
        isBlueLightOn: 0,
        alertDisplayed: 'string',
        setTempOnDisplay: 0,
        is5AdaptersPresents: true,
      },
      inboundTransitSheets: [
        {
          checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
          date: {
            year: 0,
            month: 0,
            day: 0,
            dayOfWeek: 0,
            dayOfYear: 0,
            dayNumber: 0,
          },
          time: {
            hour: 0,
            minute: 0,
            second: 0,
            millisecond: 0,
            microsecond: 0,
            nanosecond: 0,
            ticks: 0,
          },
          sealNumber: 'string',
          signature: 'string',
          name: 'hansi',
          batteryStatusInPercent: 0,
          inboundCheckAirport: 'string',
          isContainerOperating: true,
          isContainerDamaged: true,
          displayedTemp: 0,
          blueLight: 0,
          isAlarmDisplayed: true,
        },
        {
          checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66a2ew4e',
          date: {
            year: 0,
            month: 0,
            day: 0,
            dayOfWeek: 0,
            dayOfYear: 0,
            dayNumber: 0,
          },
          time: {
            hour: 0,
            minute: 0,
            second: 0,
            millisecond: 0,
            microsecond: 0,
            nanosecond: 0,
            ticks: 0,
          },
          sealNumber: 'string',
          signature: 'string',
          name: 'hansi',
          batteryStatusInPercent: 0,
          inboundCheckAirport: 'string',
          isContainerOperating: true,
          isContainerDamaged: true,
          displayedTemp: 0,
          blueLight: 0,
          isAlarmDisplayed: true,
        },
      ],
      destinationHandlingAgentSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'string',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        inboundCheckAirport: 'string',
        isContainerOperating: true,
        isContainerDamaged: true,
        displayedTemp: 0,
        inboundCheckAirportCode: 'string',
        blueLight: 0,
        isAlarmDisplayed: true,
        setTempOnDisplay: 0,
      },
      destinationConsigneeSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'string',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        isContainerDamaged: true,
        isContainerOperating: true,
        displayTemp: 0,
        is5AdaptersPresents: true,
        recipientname: 'hansi',
        recipientSignature: 'string',
      },
    });
  }

  public mockGetShipment(shipmentCode: string): Observable<ShipmentDto> {
    return of({
      uldIdList: ['ULD1', 'ULD2', 'ULD3'],
    });
  }
}
