import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { SheetDto } from 'src/model/sheetDto';
import { ShipmentDto } from 'src/model/shipmentDto';

@Injectable({
  providedIn: 'root',
})
export class ScanService {
  public constructor(private http: HttpClient) {}

  public getULDs(shipmentCode: string) {
    //return this.http.get(`https://cat-fact.herokuapp.com/facts/`);
    return of({
      checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
      preparationSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'C525123',
        signature: 'string',
        name: 'Nikolai Weidner',
        batteryStatusInPercent: 100,
        uldNumber: 'RKN61424PC',
        awbNumber: 0,
        isBatteryCharged: true,
        isContainerDamaged: true,
        routing: ['string'],
        goodsPrecooledAtTemps: 0,
        uldPrecooledTemp: 0,
        tempSetting: 0,
        acceptedTempRange: 0,
        emergencyPhone: 'string',
      },
      originHandlingAgentSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'C525123',
        signature: 'string',
        name: 'Hansi',
        batteryStatusInPercent: 0,
        isContainerDamaged: true,
        isContainerOperating: true,
        displayTemp: 0,
        isAlert: true,
        isBlueLightOn: 0,
        alertDisplayed: 'string',
        setTempOnDisplay: 0,
        is5AdaptersPresents: true,
      },
      inboundTransitSheets: [
        {
          checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
          date: {
            year: 0,
            month: 0,
            day: 0,
            dayOfWeek: 0,
            dayOfYear: 0,
            dayNumber: 0,
          },
          time: {
            hour: 0,
            minute: 0,
            second: 0,
            millisecond: 0,
            microsecond: 0,
            nanosecond: 0,
            ticks: 0,
          },
          sealNumber: 'C525123',
          signature: 'string',
          name: 'hansi',
          batteryStatusInPercent: 0,
          inboundCheckAirport: 'string',
          isContainerOperating: true,
          isContainerDamaged: true,
          displayedTemp: 0,
          blueLight: 0,
          isAlarmDisplayed: true,
        },
      ],
      destinationHandlingAgentSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'C525123',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        inboundCheckAirport: 'string',
        isContainerOperating: true,
        isContainerDamaged: true,
        displayedTemp: 0,
        inboundCheckAirportCode: 'string',
        blueLight: 0,
        isAlarmDisplayed: true,
        setTempOnDisplay: 0,
      },
      destinationConsigneeSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'C525123',
        signature: 'string',
        name: 'hansi',
        batteryStatusInPercent: 0,
        isContainerDamaged: true,
        isContainerOperating: true,
        displayTemp: 0,
        is5AdaptersPresents: true,
        recipientname: 'hansi',
        recipientSignature: 'string',
      },
    });
  }

  public mockgetChecksheet(uldId: string): Observable<SheetDto> {
    return of({
      checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
      preparationSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'C525123',
        signature: 'string',
        name: 'string',
        batteryStatusInPercent: 0,
        uldNumber: 'RKN61424PC',
        awbNumber: 0,
        isBatteryCharged: true,
        isContainerDamaged: true,
        routing: ['string'],
        goodsPrecooledAtTemps: 0,
        uldPrecooledTemp: 0,
        tempSetting: 0,
        acceptedTempRange: 'string',
        emergencyPhone: 'string',
      },
      originHandlingAgentSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 2023,
          month: 11,
          day: 26,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 9,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'C525123',
        signature: 'string',
        name: 'Nikolai Weidner',
        batteryStatusInPercent: 0,
        isContainerDamaged: false,
        isContainerOperating: false,
        displayedTemp: 4,
        isAlert: true,
        blueLight: 0,
        alertDisplayed: 'No Alarm',
        setTempOnDisplay: 4,
        is5AdaptersPresents: true,
      },
      transitSheets: [
        {
          inboundTransitSheetModel: {
            checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
            date: {
              year: 0,
              month: 0,
              day: 0,
              dayOfWeek: 0,
              dayOfYear: 0,
              dayNumber: 0,
            },
            time: {
              hour: 0,
              minute: 0,
              second: 0,
              millisecond: 0,
              microsecond: 0,
              nanosecond: 0,
              ticks: 0,
            },
            sealNumber: 'C525123',
            signature: 'string',
            name: 'string',
            batteryStatusInPercent: 0,
            isContainerOperating: true,
            isContainerDamaged: true,
            displayedTemp: 0,
            inboundCheckAirportCode: 'JFK',
            blueLight: 0,
            isAlarmDisplayed: true,
          },
          outboundTransitSheetModel: {
            checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
            date: {
              year: 0,
              month: 0,
              day: 0,
              dayOfWeek: 0,
              dayOfYear: 0,
              dayNumber: 0,
            },
            time: {
              hour: 0,
              minute: 0,
              second: 0,
              millisecond: 0,
              microsecond: 0,
              nanosecond: 0,
              ticks: 0,
            },
            sealNumber: 'C525123',
            signature: 'string',
            name: 'string',
            batteryStatusInPercent: 0,
            isContainerOperating: true,
            isContainerDamaged: true,
            displayedTemp: 0,
            blueLight: 0,
            isAlarmDisplayed: true,
            outboundCheckAirportCode: 'JFK',
          },
        },
        {
          inboundTransitSheetModel: {
            checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
            date: {
              year: 0,
              month: 0,
              day: 0,
              dayOfWeek: 0,
              dayOfYear: 0,
              dayNumber: 0,
            },
            time: {
              hour: 0,
              minute: 0,
              second: 0,
              millisecond: 0,
              microsecond: 0,
              nanosecond: 0,
              ticks: 0,
            },
            sealNumber: 'C525123',
            signature: 'string',
            name: 'string',
            batteryStatusInPercent: 0,
            isContainerOperating: true,
            isContainerDamaged: true,
            displayedTemp: 0,
            inboundCheckAirportCode: 'LGA',
            blueLight: 0,
            isAlarmDisplayed: true,
          },
          outboundTransitSheetModel: {
            checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
            date: {
              year: 0,
              month: 0,
              day: 0,
              dayOfWeek: 0,
              dayOfYear: 0,
              dayNumber: 0,
            },
            time: {
              hour: 0,
              minute: 0,
              second: 0,
              millisecond: 0,
              microsecond: 0,
              nanosecond: 0,
              ticks: 0,
            },
            sealNumber: 'C525123',
            signature: 'string',
            name: 'string',
            batteryStatusInPercent: 0,
            isContainerOperating: true,
            isContainerDamaged: true,
            displayedTemp: 0,
            blueLight: 0,
            isAlarmDisplayed: true,
            outboundCheckAirportCode: 'LGA',
          },
        },
      ],
      destinationHandlingAgentSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'C525123',
        signature: 'string',
        name: 'string',
        batteryStatusInPercent: 0,
        isContainerOperating: true,
        isContainerDamaged: true,
        displayedTemp: 0,
        inboundCheckAirportCode: 'string',
        blueLight: 0,
        isAlarmDisplayed: true,
        setTempOnDisplay: 0,
      },
      destinationConsigneeSheet: {
        checkSheetId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        date: {
          year: 0,
          month: 0,
          day: 0,
          dayOfWeek: 0,
          dayOfYear: 0,
          dayNumber: 0,
        },
        time: {
          hour: 0,
          minute: 0,
          second: 0,
          millisecond: 0,
          microsecond: 0,
          nanosecond: 0,
          ticks: 0,
        },
        sealNumber: 'C525123',
        signature: 'string',
        name: 'string',
        batteryStatusInPercent: 0,
        isContainerDamaged: true,
        isContainerOperating: true,
        displayedTemp: 0,
        is5AdaptersPresents: true,
        recipientName: 'string',
        recipientSignature: 'string',
      },
    });
  }

  public mockGetShipment(shipmentCode: string): Observable<ShipmentDto> {
    // return of({
    //   uldIdList: ['RKN61424PC', 'RKN61425PC', 'RKN61426PC'],
    // });
    return of({
      uldDictionary: {
        ['RKN61424PC']: 'RKN61424PC',
        ['RKN61425PC']: 'RKN61425PC',
        ['RKN61426PC']: 'RKN61426PC',
      },
    }); // todo
  }
}
